#!/usr/bin/env python

#####################################################################################
#
# Copyright (c) 2011 Open Technologies Bulgaria, Ltd. <http://otb.bg>
# Author: Alexander Todorov <atodorov()otb.bg>
#
# Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
#####################################################################################

__version__ = 0.1

import os
import sys
import json
import urllib
import httplib
from exceptions import BaseException
from pip.util import get_installed_distributions

data = {
    'name' : os.environ['OPENSHIFT_APP_NAME'],
    'uuid' : os.environ['OPENSHIFT_APP_UUID'],
    'type' : os.environ['OPENSHIFT_APP_TYPE'],
    'url'  : os.environ['OPENSHIFT_APP_DNS'],
    'vendor' : 0, # Red Hat OpenShift Express
    'installed' : [],
}

for dist in get_installed_distributions(local_only=True):
    data['installed'].append({'n' : dist.project_name, 'v' : dist.version})


json_data = json.dumps(data)


params = urllib.urlencode({'json_data' : json_data})

#todo: set username

conn = httplib.HTTPSConnection('cvmon-otb.rhcloud.com')
conn.request('POST', '/application/register', params)
response = conn.getresponse()

if (response.status != 200) or (not response.getheader('Content-type').startswith('application/json')):
    raise BaseException('Communication failed - %s' % response.read())

result = json.loads(response.read())
print result['message']
sys.exit(result['exit_code'])
