#!/usr/bin/env python

#####################################################################################
#
# Copyright (c) 2011-2013, Alexander Todorov <atodorov@nospam.dif.io>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#####################################################################################

import sys
from common_difio import difio_register
from difio_openshift_python import version

data = {
    'user_id'    : int(os.environ['DIFIO_USER_ID']),
    'app_name'   : os.environ['OPENSHIFT_GEAR_NAME'],
    'app_uuid'   : os.environ['OPENSHIFT_GEAR_UUID'],
    'app_type'   : 'python-%d.%d.%d' % (sys.version_info[0], sys.version_info[1], sys.version_info[2]),
    'app_url'    : 'http://%s' % os.environ['OPENSHIFT_GEAR_DNS'],
    'app_vendor' : 0, # Red Hat OpenShift
    'pkg_type'   : 0, # Python PyPI
    'installed'  : [],
}

excluded_names = [os.environ['OPENSHIFT_GEAR_NAME'].lower()]
if os.environ.has_key('DIFIO_APP_NAME'):
    excluded_names.append(os.environ['DIFIO_APP_NAME'].lower())

difio_register(data, "%s/%s" % (version.name, version.version), excluded_names)
