#!/usr/bin/env python

#####################################################################################
#
# Copyright (c) 2011-2012, Alexander Todorov <atodorov()otb.bg>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#####################################################################################

import os
import sys
import json
import urllib
import httplib
from exceptions import BaseException
from pip.util import get_installed_distributions

data = {
    'user_id'    : int(os.environ['MONUPCO_USER_ID']),
    'app_name'   : os.environ['OPENSHIFT_APP_NAME'],
    'app_uuid'   : os.environ['OPENSHIFT_APP_UUID'],
    'app_type'   : os.environ['OPENSHIFT_APP_TYPE'],
    'app_url'    : 'http://%s' % os.environ['OPENSHIFT_APP_DNS'],
    'app_vendor' : 0, # Red Hat OpenShift Express
    'pkg_type'   : 0, # Python PyPI
    'installed'  : [],
}

for dist in get_installed_distributions(local_only=True):
    # skip the package for the application itself
    if dist.project_name != os.environ['MONUPCO_APP_NAME']:
        data['installed'].append({'n' : dist.project_name, 'v' : dist.version})

json_data = json.dumps(data)
params = urllib.urlencode({'json_data' : json_data})

conn = httplib.HTTPSConnection('monupco-otb.rhcloud.com')
conn.request('POST', '/application/register/', params)
response = conn.getresponse()

if (response.status != 200) or (not response.getheader('Content-type').startswith('application/json')):
    raise BaseException('Communication failed - %s' % response.read())

result = json.loads(response.read())
print result['message']
sys.exit(result['exit_code'])
